version: '3.3'

services:
  db:
    image: mysql:8.0.21
    restart: always
    environment:
      MYSQL_DATABASE: sip_db
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:5.0.4
    restart: always
    ports:
      - 80:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  sip:
    image: sip
    restart: always
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/sip_db?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
